services:
  traefik:
    image: traefik:v3.6.2
    tty: true
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8070:8080"
    environment:
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/dynamic.yml:/dynamic/dynamic.yml:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/logs:/logs/traefik
      - ./certs:/certs
  chat-server:
    build: .
    container_name: chat-server
    ports:
      - "3490:3490"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.chat-server.rule=HostSNI(`*`)"
      
      # 2. Point to your new entrypoint (the one on port 3490)
      - "traefik.tcp.routers.chat-server.entrypoints=chat-entry"
      
      # 3. Map it to the internal port your C code listens on
      - "traefik.tcp.routers.chat-server.service=chat-server-svc"
      - "traefik.tcp.services.chat-server-svc.loadbalancer.server.port=3490"
